### PR TITLE
Create vsftpd SSL certificates for SSL support, closes: #21

### LINKED ISSUE #19: Boot warnings
```
 * Starting Mount filesystems on boot                                    [ OK ]
 * Starting Signal sysvinit that the rootfs is mounted                   [ OK ]
 * Starting Clean /tmp directory                                         [ OK ]
 * Stopping Clean /tmp directory                                         [ OK ]
 * Starting Signal sysvinit that virtual filesystems are mounted         [ OK ]
 * Starting Signal sysvinit that virtual filesystems are mounted         [ OK ]
 * Starting Bridge udev events into upstart                              [ OK ]
 * Stopping Track if upstart is running in a container                   [ OK ]
 * Starting Signal sysvinit that local filesystems are mounted           [ OK ]
 * Starting device node and kernel event manager                         [ OK ]
 * Starting Signal sysvinit that remote filesystems are mounted          [ OK ]
 * Starting load modules from /etc/modules                               [ OK ]
 * Starting cold plug devices                                            [ OK ]
 * Starting log initial device creation                                  [ OK ]
 * Starting D-Bus system message bus                                     [ OK ]
 * Stopping Mount filesystems on boot                                    [ OK ]
 * Stopping load modules from /etc/modules                               [ OK ]
 * Starting flush early job output to logs                               [ OK ]
 * Starting SystemD login management service                             [ OK ]
 * Stopping cold plug devices                                            [ OK ]
 * Stopping flush early job output to logs                               [ OK ]
 * Stopping log initial device creation                                  [ OK ]
 * Starting load fallback graphics devices                               [ OK ]
 * Starting configure network device security                            [ OK ]
 * Stopping load fallback graphics devices                               [ OK ]
 * Starting save udev log and update rules                               [ OK ]
 * Stopping save udev log and update rules                               [ OK ]
 * Starting Send an event to indicate plymouth is up                     [ OK ]
 * Stopping Send an event to indicate plymouth is up                     [ OK ]
 * Starting configure network device security                            [ OK ]
 * Starting system logging daemon                                        [ OK ]
 * Starting configure network device security                            [ OK ]
 * Starting configure network device                                     [ OK ]
 * Starting configure network device                                     [ OK ]
 * Starting Mount network filesystems                                    [ OK ]
 * Starting Failsafe Boot Delay                                          [ OK ]
 * Starting Updates server IP in /home/rtorrent/.rtorrent.rc             [ OK ]
 * Stopping Mount network filesystems                                    [ OK ]
 * Starting Mount network filesystems                                    [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Stopping Failsafe Boot Delay                                          [ OK ]
 * Starting System V initialisation compatibility                        [ OK ]
 * Starting configure virtual network devices                            [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Stopping Mount network filesystems                                    [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [fail]
 * Stopping vsftpd daemon                                                [ OK ]
 * Starting Bridge socket events into upstart                            [ OK ]
 * Starting Bridge file events into upstart                              [ OK ]
 * Stopping Updates server IP in /home/rtorrent/.rtorrent.rc             [ OK ]
 * Stopping synchronizes kernel modules                                  [ OK ]
 * Stopping System V initialisation compatibility                        [ OK ]
 * Starting System V runlevel compatibility                              [ OK ]
 * Starting save kernel messages                                         [ OK ]
 * Starting generate and fetch needed ssh keys                           [ OK ]
 * Starting regular background program processing daemon                 [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Stopping save kernel messages                                         [ OK ]
 * Starting The PHP FastCGI Process Manager                              [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
Starting supervisor:  * Starting vsftpd daemon                           [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [ OK ]
 * Starting vsftpd daemon                                                [fail]
 * Stopping vsftpd daemon                                                [ OK ]
supervisord.
 * Starting NTP server ntpd                                              [ OK ]
 * Stopping System V runlevel co
Ubuntu 14.04.2 LTS elegant-visvesvaraya ttyS0
```

### LINKED ISSUE #21: sftpd not starting
The sftpd service is not launching on startup.

```
$ /usr/sbin/vsftpd
500 OOPS: SSL: cannot load RSA certificate
```

Commenting this lines into /etc/vsftpd.conf seems to fix the issue.
```
#ssl_enable=YES
```

I believe this was introduced by 2aba94462abb5ce5a9dabea141370a0f23187990 (#14)

### PR DESCRIPTION
**Pull request by brmzkw**
Fix #19
Fix #21

### CODE REVIEW

**Comment by moul** [comment]
LGTM

**Comment by QuentinPerez** [comment]
LGTM

**Comment by hsanjuan** [comment]
You could have used 2048 for the RSA key length?

**Comment by brmzkw** [comment]
done in 1e9e1304d526d88ec0

**Pull request merged**
